/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCard: typeof import('element-ui/lib/card')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElRow: typeof import('element-ui/lib/row')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TInput: typeof import('./components/ElementUI/TInput.vue')['default']
  }
}
