/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCard: typeof import('element-ui/lib/card')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElMenuItemGroup: typeof import('element-ui/lib/menu-item-group')['default']
    ElRow: typeof import('element-ui/lib/row')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    'IMdi:fileImageOutline': typeof import('~icons/mdi/file-image-outline')['default']
    'IMdi:languageCss3': typeof import('~icons/mdi/language-css3')['default']
    'IMdi:vuejs': typeof import('~icons/mdi/vuejs')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
