info:
  contact: {}
  license: {}
paths:
  /auth:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 获取 token
      tags:
      - token
  /captcha:
    get:
      consumes:
      - application/json
      description: 通过 github.com/dchest/captcha 插件
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 获取验证码 id
      tags:
      - 验证码
  /captcha/:captchaId:
    get:
      consumes:
      - application/json
      description: 通过 github.com/dchest/captcha 插件
      parameters:
      - description: 验证码id
        in: path
        name: captchaId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 获取验证码图片
      tags:
      - 验证码
swagger: "2.0"
